/* Part of UML/Dot, a program to generate UML class diagrams from Java source.
 * Copyright (C) 2003 Walter Stroebel
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */
package net.sf.umldot.ui;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.*;
import net.sf.umldot.DUElement;
import net.sf.umldot.DUObject;

/**
 *
 * @author  walter
 */
public class ClassEditDialog extends JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    /** The current object */
    public final DUObject ob;
    /** Creates new form ClassEditDialog */
    public ClassEditDialog(Frame parent, boolean modal, DUObject ob) {
        super(parent, modal);
        this.ob = ob;
        initComponents();
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** never too big */
    private Dimension getMaxDimensions()
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        dim.height -= 120;
        dim.width -= 100;
        return dim;
    }
    
    /** get variables */
    private ListModel getVariablesList() {
        return new AbstractListModel() {
            public Object getElementAt(int index) {
                return ob.getVariables().get(index);
            }
            public int getSize() {
                return ob.getVariables().size();
            }
        };
    }
    /** get methods */
    private ListModel getMethodsList() {
        return new AbstractListModel() {
            public Object getElementAt(int index) {
                return ob.getMethods().get(index);
            }
            public int getSize() {
                return ob.getMethods().size();
            }
        };
    }
    /** get constructors */
    private ListModel getConstructorsList() {
        return new AbstractListModel() {
            public Object getElementAt(int index) {
                return ob.getConstructors().get(index);
            }
            public int getSize() {
                return ob.getConstructors().size();
            }
        };
    }
    
    private JScrollPane textArea (String s) {
        JScrollPane ret = new JScrollPane();
        ret.setMinimumSize(new Dimension (80, 80));
        ret.setPreferredSize(new Dimension (400, 266));
        ret.setViewportView(new JTextArea(s));
        return ret;
    }
    
    private void showElement(DUElement elm) {
        lbSelName.setText(elm.getName());
        lbSelType.setText(elm.getTypeFullName());
        lbSelDoc.setText(elm.getDocumentation());
        pack ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDoc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsVars = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsCons = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsMeths = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbSelName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbSelType = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbSelDoc = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jPanel1.setMaximumSize(getMaxDimensions());
        jPanel1.setPreferredSize(getMaxDimensions());
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("<html><h1>"+ob.getTypeFullName ()+"</h1></html>");
        lbTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(lbTitle);

        taDoc.setText(ob.getDocumentation());
        jScrollPane5.setViewportView(taDoc);

        jPanel1.add(jScrollPane5);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(80, 80));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 266));
        lsVars.setModel(getVariablesList());
        lsVars.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lsVars.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsVarsValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(lsVars);

        jPanel1.add(jScrollPane1);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(80, 80));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(400, 266));
        lsCons.setModel(getConstructorsList());
        lsCons.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsConsValueChanged(evt);
            }
        });

        jScrollPane3.setViewportView(lsCons);

        jPanel1.add(jScrollPane3);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(80, 80));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 266));
        lsMeths.setModel(getMethodsList());
        lsMeths.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsMethsValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(lsMeths);

        jPanel1.add(jScrollPane2);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setLabelFor(lbSelName);
        jLabel5.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        lbSelName.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(lbSelName, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setLabelFor(lbSelType);
        jLabel6.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(lbSelType, gridBagConstraints);

        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setLabelFor(lbSelDoc);
        jLabel7.setText("Doc.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(100, 100));
        lbSelDoc.setText(" ");
        jScrollPane4.setViewportView(lbSelDoc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane4, gridBagConstraints);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void lsMethsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsMethsValueChanged
        DUElement elm = (DUElement)((JList) evt.getSource()).getSelectedValue();
        lsVars.clearSelection();
        lsCons.clearSelection();
        // lsMeths.clearSelection();
        if (elm != null) {
            showElement (elm);
        }
    }//GEN-LAST:event_lsMethsValueChanged
    
    private void lsConsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsConsValueChanged
        DUElement elm = (DUElement)((JList) evt.getSource()).getSelectedValue();
        lsVars.clearSelection();
        // lsCons.clearSelection();
        lsMeths.clearSelection();
        if (elm != null) {
            showElement (elm);
        }
    }//GEN-LAST:event_lsConsValueChanged
    
    private void lsVarsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsVarsValueChanged
        DUElement elm = (DUElement)((JList) evt.getSource()).getSelectedValue();
        // lsVars.clearSelection();
        lsCons.clearSelection();
        lsMeths.clearSelection();
        if (elm != null) {
            showElement (elm);
        }
    }//GEN-LAST:event_lsVarsValueChanged
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea lbSelDoc;
    private javax.swing.JLabel lbSelName;
    private javax.swing.JLabel lbSelType;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JList lsCons;
    private javax.swing.JList lsMeths;
    private javax.swing.JList lsVars;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea taDoc;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
