/* Part of UML/Dot, a program to generate UML class diagrams from Java source.
 * Copyright (C) 2003 Walter Stroebel
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */
package net.sf.umldot.ui;

import java.awt.Frame;
import java.beans.PropertyVetoException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.umldot.DUElement;
import net.sf.umldot.DUObject;
import net.sf.umldot.DURelation;
import net.sf.umldot.Project;

/**
 *
 * @author  walter
 */
public class EditRelation extends JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    /** The relation being (re) defined */
    public DURelation rel;
    /** Last selected element */
    public DUElement selElm = null;
    /** Last selected FROM element */
    public DUObject from = null;
    /** Last selected TO element */
    public DUObject to = null;
    
    /** Creates new form EditRelation */
    public EditRelation(Frame parent, boolean modal, DURelation rel) {
        super(parent, modal);
        this.rel = rel;
        if (rel.getFrom() != null && rel.getTo() != null) {
            from = rel.getFrom();
            to = rel.getTo();
        } else {
            from = DUObject.findOrCreate(Object.class);
            to = from;
        }
        initComponents();
        switch (rel.getRank()) {
            case DURelation.RANK_NONE:
                cbRank.setSelectedItem("none");
                break;
            case DURelation.RANK_INVERTED:
                cbRank.setSelectedItem("inverted");
                break;
            default:
                cbRank.setSelectedItem("normal");
                break;
        }
        cbRelType.setSelectedItem(rel.getTypeFullName());
        cbFromMult.setSelectedItem(rel.getFromMult());
        cbToMult.setSelectedItem(rel.getToMult());
        Project.getInstance().swProps.restoreLocationAndSize(this);
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree (Project.getInstance().objectTree);
        tfNamedObject = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btSetFrom = new javax.swing.JButton();
        btSetTo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfFromName = new javax.swing.JTextField();
        cbFromMult = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfToName = new javax.swing.JTextField();
        cbToMult = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfRelName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbRelType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taComment = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cbRank = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tfNamedObject.setBackground(new java.awt.Color(204, 204, 255));
        tfNamedObject.setEditable(false);
        tfNamedObject.setPreferredSize(new java.awt.Dimension(400, 20));
        jPanel1.add(tfNamedObject, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btSetFrom.setText("=> From");
        btSetFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetFromActionPerformed(evt);
            }
        });

        jPanel2.add(btSetFrom);

        btSetTo.setText("=> To");
        btSetTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetToActionPerformed(evt);
            }
        });

        jPanel2.add(btSetTo);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("ObjectSelector", jPanel1);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("From");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel1, gridBagConstraints);

        tfFromName.setBackground(new java.awt.Color(204, 204, 255));
        tfFromName.setEditable(false);
        tfFromName.setText(from.getTypeFullName ());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(tfFromName, gridBagConstraints);

        cbFromMult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0..1", "0..*", "1..*" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        jPanel3.add(cbFromMult, gridBagConstraints);

        jLabel2.setText("To");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel2, gridBagConstraints);

        tfToName.setBackground(new java.awt.Color(204, 204, 255));
        tfToName.setEditable(false);
        tfToName.setText(to.getTypeFullName ());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(tfToName, gridBagConstraints);

        cbToMult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0..1", "0..*", "1..*" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        jPanel3.add(cbToMult, gridBagConstraints);

        jLabel3.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel3, gridBagConstraints);

        tfRelName.setText(rel.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(tfRelName, gridBagConstraints);

        jLabel4.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel4, gridBagConstraints);

        cbRelType.setModel(new javax.swing.DefaultComboBoxModel(DURelation.relationTypes));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(cbRelType, gridBagConstraints);

        jLabel5.setText("Comment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel5, gridBagConstraints);

        taComment.setColumns(60);
        taComment.setText(rel.getDocumentation ());
        jScrollPane2.setViewportView(taComment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane2, gridBagConstraints);

        jLabel6.setText("Rank");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel6, gridBagConstraints);

        cbRank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "normal", "inverted", "none" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(cbRank, gridBagConstraints);

        jTabbedPane1.addTab("Relation", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void btSetToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetToActionPerformed
        if (selElm instanceof DUObject) {
            to = (DUObject) selElm;
            tfToName.setText(to.getTypeFullName());
        }
    }//GEN-LAST:event_btSetToActionPerformed
    
    private void btSetFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetFromActionPerformed
        if (selElm instanceof DUObject) {
            from = (DUObject) selElm;
            tfFromName.setText(from.getTypeFullName());
        }
    }//GEN-LAST:event_btSetFromActionPerformed
    
    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        try {
            selElm = (DUElement) jTree1.getLastSelectedPathComponent();
            tfNamedObject.setText(selElm.getTypeFullName());
        } catch (Exception ignore) {
            ignore.printStackTrace();
            selElm = null;
            tfNamedObject.setText("???");
        }
    }//GEN-LAST:event_jTree1ValueChanged
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        rel.setName(tfRelName.getText());
        try {
            rel.setTypeFullName((String) cbRelType.getSelectedItem());
        } catch (PropertyVetoException veto) {
            JOptionPane.showMessageDialog(this, veto.getMessage()+
            "\nFrom: "+veto.getPropertyChangeEvent().getOldValue()+
            "\nTo: "+veto.getPropertyChangeEvent().getNewValue(),
            "Bad relation type", JOptionPane.ERROR_MESSAGE);
        }
        rel.setFrom(from);
        rel.setTo(to);
        rel.setDocumentation(taComment.getText());
        rel.setFromMult((String) cbFromMult.getSelectedItem());
        rel.setToMult((String) cbToMult.getSelectedItem());
        if (((String) cbRank.getSelectedItem()).equals("normal")) {
            rel.setRank(DURelation.RANK_NORMAL);
        }
        if (((String) cbRank.getSelectedItem()).equals("inverted")) {
            rel.setRank(DURelation.RANK_INVERTED);
        }
        if (((String) cbRank.getSelectedItem()).equals("none")) {
            rel.setRank(DURelation.RANK_NONE);
        }
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        Project.getInstance().swProps.rememberLocationAndSize(this);
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSetFrom;
    private javax.swing.JButton btSetTo;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox cbFromMult;
    private javax.swing.JComboBox cbRank;
    private javax.swing.JComboBox cbRelType;
    private javax.swing.JComboBox cbToMult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea taComment;
    private javax.swing.JTextField tfFromName;
    private javax.swing.JTextField tfNamedObject;
    private javax.swing.JTextField tfRelName;
    private javax.swing.JTextField tfToName;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
